--/***********************************************************
--	DQL (script d'interrogation des données)
--	Auteurs:		Gabriel Frenette et Guillaume Ouellet 	
--***********************************************************/