--/***********************************************************
--	DML Execution (Execution du script de mise-à-jour des données)
--	Auteurs:		Gabriel Frenette et Guillaume Ouellet 	
--***********************************************************/