--/***********************************************************
--	DDL Create (Creation des tables)
--	Auteurs:		Gabriel Frenette et Guillaume Ouellet 	
--***********************************************************/