--/***********************************************************
--	DDL Drop (Destruction des tables)
--	Auteurs:		Gabriel Frenette et Guillaume Ouellet 	
--***********************************************************/